### ISSUE TITLE
Ticket Value must show Deparment wise during Patient Registration

### ISSUE THREAD

**Issue by RHCF-Parnab** [kolkata-foundation/kf-medical#12]

**Comment by RHCF-Parnab** [comment]
For Example we have 4 departments GP, EYE, Homeo, dental. Every department have same/ different ticket value. And It can be differ centre Wise.

**Comment by banerjed** [comment]
This feature request (a concept of a fixed-cost ticket) is too specific to RHCF's current operations and not a general requirement of the software. Recommend that this be handled outside of the software -- the current software allows capturing patient copay, which is a generic concept.
