### ISSUE TITLE
Multiple Ticketing Option Required

### ISSUE THREAD

**Issue by RHCF-Parnab** [kolkata-foundation/kf-medical#19]
Patient can Purchase multiple tickets when he/she visit the helth centres. And The Ticket Value will Multiply with Number of Tickets.

**Comment by banerjed** [comment]
This is not a required feature. The concept of a "fixed cost ticket" (or set of tickets) is very specific to RHCF's current operations and should be handled outside the software. The software currently allows capturing patient-copay, which is a generic concept.
