### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by nityanantan23** [kolkata-foundation/kf-medical#2]
TypeScript error in kf-medical-main/frontend/src/App.tsx(25,6):
No overload matches this call.
  Overload 1 of 2, '(props: ProviderProps<AnyAction> | Readonly<ProviderProps<AnyAction>>): Provider<AnyAction>', gave the following error.
    Type '{ children: Element; store: any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<AnyAction>> & Readonly<ProviderProps<AnyAction>>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<AnyAction>> & Readonly<ProviderProps<AnyAction>>'.
  Overload 2 of 2, '(props: ProviderProps<AnyAction>, context: any): Provider<AnyAction>', gave the following error.
    Type '{ children: Element; store: any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<AnyAction>> & Readonly<ProviderProps<AnyAction>>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider<AnyAction>> & Readonly<ProviderProps<AnyAction>>'.  TS2769

    23 | export default function App(props) {
    24 |   return (
     25 |     <Provider store={store}>
    26 |       <AppWithRedux {...props} />
    27 |     </Provider>
    28 |   );

**Comment by banerjed** [comment]
The code has changed substantially since then..can you please retry?
